# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reduceGeneExpression <- function(expression, reduced_dim = 30L, method = 1L, iters = 10L) {
    .Call(`_ACTIONet_reduceGeneExpression`, expression, reduced_dim, method, iters)
}

runsimplexRegression <- function(A, B) {
    .Call(`_ACTIONet_runsimplexRegression`, A, B)
}

runSPA <- function(A, k) {
    .Call(`_ACTIONet_runSPA`, A, k)
}

runAA <- function(A, W0) {
    .Call(`_ACTIONet_runAA`, A, W0)
}

runACTION <- function(S_r, k_min = 2L, k_max = 20L, thread_no = 4L) {
    .Call(`_ACTIONet_runACTION`, S_r, k_min, k_max, thread_no)
}

runACTION_withBatch <- function(S_r, batch, k_min = 2L, k_max = 20L, max_correction_rounds = 3L, lambda = 1, numThreads = 4L) {
    .Call(`_ACTIONet_runACTION_withBatch`, S_r, batch, k_min, k_max, max_correction_rounds, lambda, numThreads)
}

frSVD <- function(A, dim, iters = 5L, seed = 0L) {
    .Call(`_ACTIONet_frSVD`, A, dim, iters, seed)
}

set_seed <- function(seed) {
    invisible(.Call(`_ACTIONet_set_seed`, seed))
}

buildACTIONet <- function(H_stacked, kNN = 30L, thread_no = 8L) {
    .Call(`_ACTIONet_buildACTIONet`, H_stacked, kNN, thread_no)
}

buildAdaptiveACTIONet <- function(H_stacked, LC = 1.0, epsilon = 0.0, thread_no = 8L, auto_adjust_LC = FALSE, sym_method = "OR") {
    .Call(`_ACTIONet_buildAdaptiveACTIONet`, H_stacked, LC, epsilon, thread_no, auto_adjust_LC, sym_method)
}

layoutACTIONet <- function(G, S_r, compactness_level = 50L, n_epochs = 100L, thread_no = 8L) {
    .Call(`_ACTIONet_layoutACTIONet`, G, S_r, compactness_level, n_epochs, thread_no)
}

reconstructArchetypes <- function(S, C_trace, H_trace, z_threshold = 1.0) {
    .Call(`_ACTIONet_reconstructArchetypes`, S, C_trace, H_trace, z_threshold)
}

assessFeatureSets <- function(S, index_sets, rand_perm = 100L) {
    .Call(`_ACTIONet_assessFeatureSets`, S, index_sets, rand_perm)
}

phenotypeEnrichment <- function(H_stacked, phenotype_associations, rand_perm_no) {
    .Call(`_ACTIONet_phenotypeEnrichment`, H_stacked, phenotype_associations, rand_perm_no)
}

update_layout_2D <- function(coors, compactness_level = 50L, n_epochs = 100L, thread_no = 8L) {
    .Call(`_ACTIONet_update_layout_2D`, coors, compactness_level, n_epochs, thread_no)
}

computeNearestDist_edgeList <- function(H_stacked, kNN, thread_no = 8L) {
    .Call(`_ACTIONet_computeNearestDist_edgeList`, H_stacked, kNN, thread_no)
}

computeFullDist <- function(H_stacked, thread_no = 8L, verbose = 1L) {
    .Call(`_ACTIONet_computeFullDist`, H_stacked, thread_no, verbose)
}

